"""all_tables

Revision ID: d2a727cf043d
Revises: 
Create Date: 2026-04-21 16:44:22.444875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2a727cf043d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('UTILITIES', 'SUPPLIES', 'MAINTENANCE', 'TRANSPORTATION', 'MEALS', 'PROFESSIONAL_SERVICES', 'INSURANCE', 'EQUIPMENT', 'FURNITURE', 'CLEANING', 'SECURITY', 'PROGRAMS', 'TRAVEL', 'PRINTING', 'MISCELLANEOUS', name='expensecategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gl_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gl_account_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'POSTED', name='expensestatus'), nullable=False),
    sa.Column('submitted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_status', sa.Enum('OUTSTANDING', 'PARTIAL', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('journal_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_status'), ['status'], unique=False)

    op.create_table('gl_accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('account_category', sa.Enum('BANK_ACCOUNTS', 'ACCOUNTS_RECEIVABLE', 'PREPAID_EXPENSES', 'FIXED_ASSETS', 'ACCOUNTS_PAYABLE', 'SALARIES_PAYABLE', 'SHORT_TERM_DEBT', 'LONG_TERM_DEBT', 'ACCUMULATED_SURPLUS', 'RETAINED_EARNINGS', 'STUDENT_FEES', 'DONATIONS', 'GRANTS', 'OTHER_INCOME', 'SALARIES_WAGES', 'UTILITIES', 'SUPPLIES', 'REPAIRS_MAINTENANCE', 'TRANSPORT_COSTS', 'CONTRACTED_SERVICES', 'DEPRECIATION', 'OTHER_EXPENSES', name='accountcategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normal_balance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gl_accounts_account_code'), ['account_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_accounts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_gl_accounts_school_id'), ['school_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('reference_type', sa.Enum('PAYROLL_RUN', 'FEE_PAYMENT', 'EXPENSE', 'MANUAL', 'ADJUSTMENT', 'DEPRECIATION', 'PERIOD_CLOSING', 'BANK_RECONCILIATION', 'PLATFORM_SUBSCRIPTION', name='referencetype'), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_debit', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('posting_status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', 'REJECTED', name='postingstatus'), nullable=False),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejected_date', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversal_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reversed_date', sa.DateTime(), nullable=True),
    sa.Column('reversed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_posting_status'), ['posting_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_school_id'), ['school_id'], unique=False)

    op.create_table('journal_line_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('journal_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gl_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('debit_amount', sa.Float(), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_line_items_gl_account_id'), ['gl_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_items_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_line_items_school_id'), ['school_id'], unique=False)

    op.create_table('online_transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'WEBHOOK_RECEIVED', name='transactionstatus'), nullable=False),
    sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gateway_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('journal_entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('online_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_online_transactions_fee_id'), ['fee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_transactions_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_transactions_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_transactions_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_online_transactions_student_id'), ['student_id'], unique=False)

    op.create_table('payment_verifications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('match_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('webhook_payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_verifications_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_verifications_transaction_id'))

    op.drop_table('payment_verifications')
    with op.batch_alter_table('online_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_online_transactions_student_id'))
        batch_op.drop_index(batch_op.f('ix_online_transactions_school_id'))
        batch_op.drop_index(batch_op.f('ix_online_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_online_transactions_parent_id'))
        batch_op.drop_index(batch_op.f('ix_online_transactions_fee_id'))

    op.drop_table('online_transactions')
    with op.batch_alter_table('journal_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_line_items_school_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_items_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_line_items_gl_account_id'))

    op.drop_table('journal_line_items')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_school_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_reference_type'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_posting_status'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gl_accounts_school_id'))
        batch_op.drop_index(batch_op.f('ix_gl_accounts_is_active'))
        batch_op.drop_index(batch_op.f('ix_gl_accounts_account_type'))
        batch_op.drop_index(batch_op.f('ix_gl_accounts_account_code'))

    op.drop_table('gl_accounts')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_school_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_payment_status'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    op.drop_table('expenses')
    # ### end Alembic commands ###
