"""all_tables3

Revision ID: d3d12e60d1e7
Revises: b770252e5934
Create Date: 2026-05-04 03:14:13.652791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3d12e60d1e7'
down_revision: Union[str, None] = 'b770252e5934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('idx_announcement_school_published')
        batch_op.drop_index('idx_communication_school_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_class_date')
        batch_op.drop_index('idx_attendance_school_date')
        batch_op.drop_index('idx_attendance_student_date')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index('idx_class_school_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('posted_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fiscal_period_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('gl_posting_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_index('idx_fee_payment_student')
        batch_op.drop_index('idx_payment_school_date')

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_index('idx_fee_school_status')
        batch_op.drop_index('idx_fee_student_school')
        batch_op.drop_index('idx_fee_student_status')

    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('opening_balance', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('bank_reconciled_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_balance_update', sa.DateTime(), server_default=sa.func.now(), nullable=False))
        batch_op.add_column(sa.Column('bank_reconciliation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reconciliation_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index('idx_grade_school_term')
        batch_op.drop_index('idx_grade_student_subject')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.drop_index('idx_hostel_school_id')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fiscal_period_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cutoff_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_adjusting_entry', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('reversal_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_message_receiver_read')
        batch_op.drop_index('idx_message_sender_id')

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_payroll_school_period')

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index('idx_transport_route_school')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index('idx_staff_school_id')

    with op.batch_alter_table('student_parents', schema=None) as batch_op:
        batch_op.drop_index('idx_student_parent_parent_id')
        batch_op.drop_index('idx_student_parent_student_id')

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_index('idx_timetable_class_day')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_id_active')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_id_active', ['id', 'is_active'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.create_index('idx_timetable_class_day', ['class_id', 'day_of_week'], unique=False)

    with op.batch_alter_table('student_parents', schema=None) as batch_op:
        batch_op.create_index('idx_student_parent_student_id', ['student_id'], unique=False)
        batch_op.create_index('idx_student_parent_parent_id', ['parent_id'], unique=False)

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index('idx_staff_school_id', ['school_id'], unique=False)

    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index('idx_transport_route_school', ['school_id'], unique=False)

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index('idx_payroll_school_period', ['school_id', 'period_month'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_message_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('idx_message_receiver_read', ['receiver_id', 'is_read'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('reversal_reason')
        batch_op.drop_column('is_adjusting_entry')
        batch_op.drop_column('cutoff_period')
        batch_op.drop_column('fiscal_period_id')
        batch_op.drop_column('posted_ip')

    with op.batch_alter_table('hostels', schema=None) as batch_op:
        batch_op.create_index('idx_hostel_school_id', ['school_id'], unique=False)

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index('idx_grade_student_subject', ['student_id', 'subject_id'], unique=False)
        batch_op.create_index('idx_grade_school_term', ['school_id', 'academic_term_id'], unique=False)

    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.drop_column('reconciliation_notes')
        batch_op.drop_column('bank_reconciliation_date')
        batch_op.drop_column('last_balance_update')
        batch_op.drop_column('bank_reconciled_balance')
        batch_op.drop_column('opening_balance')
        batch_op.drop_column('current_balance')

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.create_index('idx_fee_student_status', ['student_id', 'status'], unique=False)
        batch_op.create_index('idx_fee_student_school', ['student_id', 'school_id'], unique=False)
        batch_op.create_index('idx_fee_school_status', ['school_id', 'status'], unique=False)

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.create_index('idx_payment_school_date', ['school_id', 'created_at'], unique=False)
        batch_op.create_index('idx_fee_payment_student', ['student_id', 'payment_date'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('gl_posting_reference')
        batch_op.drop_column('fiscal_period_id')
        batch_op.drop_column('posted_ip')
        batch_op.drop_column('posted_by')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index('idx_class_school_id', ['school_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_student_date', ['student_id', 'attendance_date'], unique=False)
        batch_op.create_index('idx_attendance_school_date', ['school_id', 'attendance_date'], unique=False)
        batch_op.create_index('idx_attendance_class_date', ['class_id', 'attendance_date'], unique=False)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('idx_communication_school_id', ['school_id'], unique=False)
        batch_op.create_index('idx_announcement_school_published', ['school_id', 'is_published'], unique=False)

    # ### end Alembic commands ###
